sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: https://oss-cn-wulanchabu.aliyuncs.com
    access-key-id: LTAI5tDZXgD6SgVydKy18N7u
    access-key-secret: EwvCmq5kswYbmxBbFbAT9nUC4kGyq7
    bucket-name: fenghun
   # AccessKey ID
    #  LTAI5tDZXgD6SgVydKy18N7u

    #  AccessKey Secret
    #  EwvCmq5kswYbmxBbFbAT9nUC4kGyq7
  redis:
     host: localhost
     port: 6379
     password: 123456
     database: 0